import type { GameCharacter } from './characters/types';
import { randomQuestionSets } from './randomQuestionSets';

export type CharacterQuestion = { id: string; text: string; answer: string };
export type QuestionKey = string;

const set = (...lines: [string, string][]): CharacterQuestion[] => lines.map(([text, answer], index) => ({ id: `q${index}`, text, answer }));

const mainQuestionSets: Record<string, CharacterQuestion[]> = {
  hunter: set(['What were you hunting?', 'A deer at first. Then I found tracks that looked human until they reached the rocks.'], ['Which trail did you take?', 'The north game trail. The markers disappear about a mile back.'], ['Why are your clothes wet?', 'I fell through creek ice. It was shallow, but something moved under it.']),
  'old-woman': set(['Why were you out in this storm?', 'I went to check on a neighbour. Her door was open and the house was empty.'], ['How do you know this cabin?', 'I lived here when I was young. The porch was smaller then.'], ['Why is your shawl dry?', 'I sheltered beneath the chapel eaves until the wind changed. Feel it yourself if you open.']),
  doctor: set(['Why are you travelling alone?', 'I was with two patients. We became separated when the wind covered the road.'], ["What's inside your bag?", 'Bandages, antibiotics, a stethoscope, and less morphine than I would like.'], ['Have you seen anyone else outside?', 'A woman near the lower road. She would not answer when I called to her.']),
  'woman-red': set(['What happened at the lodge?', 'The generator failed. Then I heard my own voice calling from the basement stairs.'], ['Why is your hand closed?', 'The kitchen key cut my palm when I fell. I am holding cloth against it.'], ['Who followed you?', 'A woman in a red coat. I never saw her face.']),
  priest: set(['Why did you leave the chapel?', 'Someone rang the bell from outside. I found the rope still tied inside the tower.'], ['Why is your cross backwards?', 'The chain twisted under my coat while I walked. I had not noticed.'], ['Did anyone travel with you?', 'A parishioner followed as far as the cemetery. He stopped when I called his name.']),
  'lost-boy': set(['Where is your teacher?', 'She went back to the bus for two other students. I waited until something started calling me.'], ['Why did you leave the road?', 'The voice came from the trees, then from behind me. I ran toward the first light I saw.'], ['What is in your backpack?', 'Schoolbooks, a dead phone, and my inhaler. You can look through it.']),
  lumberjack: set(['Why were you still at the logging camp?', 'The truck would not start. I stayed to cover the equipment before the snow buried it.'], ['What stained your hands?', 'Tree sap and oil. The red on my cuff came from catching it on a nail.'], ['What followed you?', 'I never saw it. I heard an axe strike after every seventh step.']),
  teacher: set(['Where are your students?', 'Most reached the village. Two were missing when I went back to the bus.'], ['Why carry the attendance book?', 'Their emergency contacts are inside. I could not leave it on the seat.'], ['Did you find the missing children?', 'I found their footprints. They ended together in the middle of the road.']),
  fisherman: set(['Why were you on the reservoir?', 'I was checking the lines before the storm. The warning came over the radio too late.'], ['How did your clothes get wet?', 'The ice broke near shore. Something pushed against my boot from underneath.'], ['Where is your fishing gear?', 'At the hole. I dropped everything when I heard someone climbing out behind me.']),
  musician: set(['What is in the case?', 'My guitar. The latch is broken, so keep it flat if you want to inspect it.'], ['Why did you leave the lodge?', 'The power failed during rehearsal. Music kept coming through speakers with no power.'], ['Was anyone following you?', 'I heard somebody humming the same four notes. They stopped when I turned around.']),
  student: set(['Where do you study?', 'At the college in Bellweather. I was staying in the old dormitory.'], ['Why are you outside so late?', 'The power failed. I left when somebody began trying every door on my floor.'], ["Why didn't you stay at your dorm?", 'My roommate called me from downstairs. She was asleep in the bed beside me.']),
  photographer: set(['Why did you bring the camera?', 'It was already around my neck when I ran. I did not stop to take anything else.'], ['What happened at the lodge?', 'The power failed while I was photographing the storm. After the last flash, I saw someone standing behind me in the picture.'], ['How did you reach the cabin?', 'I followed the tree line uphill. Whenever I stopped, I could hear another set of footsteps stop a few seconds later.']),
  'twin-sisters': set(['Why do you share one pair of gloves?', 'Vera lost hers crossing the creek. We each kept one hand warm and traded.'], ['Where did your car leave the road?', 'At the second bend below the pass. The guardrail was already broken.'], ['Why do you answer together?', 'Because the voice behind us could copy one of us at a time, never both.']),
  soldier: set(['What happened to your convoy?', 'The lead vehicle stopped without warning. When we regrouped, one person was standing with no assigned seat.'], ['Why is your flare pistol empty?', 'I fired twice to mark the road and once at something I could not identify.'], ['Where is the rest of your unit?', 'South of the ridge if they followed procedure. I lost radio contact twenty minutes ago.']),
  wanderer: set(['Where did you come from?', 'A road beyond the pines. I cannot see it from here anymore.'], ['Why are there no tracks behind you?', 'The wind covered them. It has been close behind me all night.'], ['How long have you been walking?', 'Since the light changed. I do not know what time that was.']),
};

export function questionsFor(character: GameCharacter): CharacterQuestion[] {
  return mainQuestionSets[character.id] ?? randomQuestionSets[character.id] ?? [];
}
