import type { GameCharacter } from './types';

export const randomCharactersA: GameCharacter[] = [
  { id: 'baker', tier: 'random', name: 'Mina Loaf', kind: 'human', personality: 'maternal, nervous', appearance: 'flour-dusted baker in a patched brown coat', backstory: 'Mina fled the village oven after dough rose with finger marks pressed from inside.', dialogue: ['I brought bread. It is probably frozen solid, but sharing makes it feel less like the end.'], inspections: ['Flour streaks her cheek beneath the snow.', 'A bread knife is wrapped in cloth.', 'She smells faintly of yeast and smoke.'], behaviors: ['Offers food before asking for warmth.', 'Watches mouths when people chew.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'miner', tier: 'random', name: 'Davor Kline', kind: 'human', personality: 'grim, superstitious', appearance: 'coal miner with a lamp clipped to his hood', backstory: 'Davor heard tapping from a sealed mine shaft spelling his daughter’s name.', dialogue: ['If you hear knocking from under the floor, do not answer that either.'], inspections: ['Coal dust darkens the lines of his palms.', 'His lamp flickers near the door.', 'He carries a canary charm with no chain.'], behaviors: ['Counts knocks in groups of three.', 'Refuses to sit with his back to stone.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'bride', tier: 'random', name: 'Evelyn Frost', kind: 'skinwalker', personality: 'sweet, rehearsed', appearance: 'bride in a torn winter veil with blue lips', backstory: 'Something found an abandoned wedding album and learned grief from the photographs.', dialogue: ['My groom is late. Everyone is late. May I wait here where it is warm?'], inspections: ['The veil has no snow on its lace.', 'Her bouquet is made of dead pine needles.', 'She smiles before jokes are spoken.'], behaviors: ['Asks guests to stand beside her for pictures.', 'Calls strangers by wedding-party titles.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'logger', tier: 'random', name: 'Greta Noll', kind: 'human', personality: 'direct, weary', appearance: 'broad-shouldered logger with red suspenders', backstory: 'Greta watched a felled tree bleed dark sap and whisper the crew roster.', dialogue: ['I know wood. Your door is scared. That should bother both of us.'], inspections: ['Fresh sawdust clings to her boots.', 'Her axe head is wrapped in wool.', 'She has a burn shaped like a branch.'], behaviors: ['Tests walls by tapping boards.', 'Warns if the cabin creaks in reply.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'photographer', tier: 'random', name: 'Theo Glass', kind: 'human', personality: 'curious, shaken', appearance: 'photographer with cracked goggles and camera bag', backstory: 'Theo photographed the treeline and developed pictures of people standing behind him.', dialogue: ['My camera caught your cabin before I saw it. That seems backwards.'], inspections: ['His camera lens is split like ice.', 'Negatives rattle in a metal case.', 'He avoids looking at reflections in glass.'], behaviors: ['Photographs footprints before they vanish.', 'Claims some guests blur on film.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'taxidermist', tier: 'random', name: 'Vera Quill', kind: 'skinwalker', personality: 'polite, clinical', appearance: 'taxidermist in a fur collar with perfect posture', backstory: 'A mimic wearing Vera’s trade learned too much about arranging empty skins.', dialogue: ['I know how to preserve things. You would be surprised what warmth can ruin.'], inspections: ['Her gloves are sewn with black thread.', 'Her eyes study proportions, not expressions.', 'She never blinks while you move.'], behaviors: ['Compliments bone structure.', 'Asks whether guests sleep deeply.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'pianist', tier: 'random', name: 'Lucien Mare', kind: 'human', personality: 'dramatic, fragile', appearance: 'pianist with long fingers wrapped in linen', backstory: 'Lucien played for an empty lodge while invisible hands turned pages beside him.', dialogue: ['I need shelter, and possibly an audience that breathes. In that order.'], inspections: ['His bandages are stained with ink, not blood.', 'He taps rhythms against his coat.', 'One fingertip is frost-black.'], behaviors: ['Keeps time with distant knocks.', 'Calms guests by tapping lullabies.'], stayNights: [1, 2], outcome: 'injure' },
  { id: 'shepherd', tier: 'random', name: 'Aksel Moor', kind: 'human', personality: 'quiet, loyal', appearance: 'shepherd wrapped in a wool blanket', backstory: 'Aksel lost his flock after every bell began ringing from a different direction.', dialogue: ['The sheep ran from something I could not see. I decided to respect their judgment.'], inspections: ['Tiny bells are tied along his belt.', 'Wool fibers stick to his eyebrows.', 'He listens low, near the floor.'], behaviors: ['Hears movement before others do.', 'Shares blunt animal wisdom.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'beekeeper', tier: 'random', name: 'Suri Vale', kind: 'human', personality: 'soft, precise', appearance: 'beekeeper in a white hood under a parka', backstory: 'Suri’s winter hives woke at midnight and formed a face against the glass.', dialogue: ['Bees know when a queen is wrong. People should learn that trick.'], inspections: ['Her veil is folded carefully in one pocket.', 'Wax seals cracks in her gloves.', 'A low hum follows her breathing.'], behaviors: ['Notices when silence becomes too organized.', 'Seals draft gaps with beeswax.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'accountant', tier: 'random', name: 'Nikolai Penn', kind: 'skinwalker', personality: 'fussy, false', appearance: 'accountant with a green visor and spotless shoes', backstory: 'This thing learned human worry from ledgers abandoned at the lodge desk.', dialogue: ['I can pay for damages. I have always believed in settling accounts.'], inspections: ['His shoes are dry to the sole.', 'Numbers are written backward on his cuff.', 'He asks for receipts in a storm.'], behaviors: ['Counts people as inventory.', 'Corrects totals no one said aloud.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'nurse', tier: 'random', name: 'Petra Loom', kind: 'human', personality: 'brisk, protective', appearance: 'nurse with a white armband and cracked lips', backstory: 'Petra evacuated patients from a clinic after the intercom began giving last words.', dialogue: ['Open or do not, but decide before my hands stop working.'], inspections: ['Her armband is marked with three names.', 'She carries disinfectant frozen into slush.', 'Her pupils track your injuries first.'], behaviors: ['Checks guests for frostbite.', 'Distrusts anyone too warm.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'conductor', tier: 'random', name: 'Bastian Rail', kind: 'human', personality: 'formal, rattled', appearance: 'train conductor in a navy cap with brass buttons', backstory: 'Bastian’s train stopped beside tracks that had been torn out twenty years earlier.', dialogue: ['I punched tickets for passengers who cast no shadow. I would like to resign.'], inspections: ['Ticket stubs spill from his pockets.', 'His brass buttons are warm.', 'He smells of metal and wet wool.'], behaviors: ['Announces time changes nobody asked for.', 'Recognizes guests from impossible passenger lists.'], stayNights: [1, 2], outcome: 'steal' },
  { id: 'lampmaker', tier: 'random', name: 'Elsa Wick', kind: 'human', personality: 'patient, hopeful', appearance: 'lampmaker carrying a tin lantern with green glass', backstory: 'Elsa repairs lamps for the village and fears one has begun attracting the wrong lost souls.', dialogue: ['Light is a promise. Tonight I am begging yours to keep its word.'], inspections: ['Her lantern flame leans toward the door.', 'Soot marks form crescents on her sleeves.', 'She smells of kerosene and rosemary.'], behaviors: ['Brightens dark corners.', 'Says some faces dim when watched.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'icefisher', tier: 'random', name: 'Oskar Pell', kind: 'skinwalker', personality: 'slow, hungry', appearance: 'ice fisher with a frozen beard and hook-scarred coat', backstory: 'A thing came up through the lake wearing Oskar’s patience like skin.', dialogue: ['There are fish beneath us even here. Everything hungry finds a hole.'], inspections: ['Water drips from him though the porch is frozen.', 'Fishhooks line his sleeves.', 'His beard does not move when he speaks.'], behaviors: ['Asks where food is stored.', 'Stares at ankles under chairs.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'seamstress', tier: 'random', name: 'Clara Thread', kind: 'human', personality: 'practical, tender', appearance: 'seamstress with needles pinned to a violet scarf', backstory: 'Clara mended coats for evacuees and found extra sleeves growing in the lining.', dialogue: ['Give me a corner and I will mend what the night has torn. Cloth, not hearts. I am not that good.'], inspections: ['Needles glint along her scarf.', 'Her thimble is dented from hard use.', 'Loose thread trails from her hem.'], behaviors: ['Repairs guest clothing.', 'Finds odd seams in mimic coats.'], stayNights: [1, 3], outcome: 'peaceful' },
];
