import type { GameCharacter } from './types';

export const randomCharactersB: GameCharacter[] = [
  { id: 'mailman', tier: 'random', name: 'Hugo Stamp', kind: 'human', personality: 'cheerful, exhausted', appearance: 'mailman with a frozen satchel and blue mittens', backstory: 'Hugo kept delivering after letters arrived from houses already empty.', dialogue: ['Neither snow nor terror nor whatever that was by the road, apparently.'], inspections: ['His satchel bulges with unopened mail.', 'Ice has sealed his mustache sideways.', 'He knows names from envelopes, not faces.'], behaviors: ['Hands out letters to guests.', 'Panics at mail addressed from the future.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'clockmaker', tier: 'random', name: 'Irina Tick', kind: 'skinwalker', personality: 'precise, hollow', appearance: 'clockmaker with tiny gears sewn into her cuffs', backstory: 'This mimic learned patience by listening to stopped clocks restart in empty rooms.', dialogue: ['Time behaves poorly here. Let me inside and I will keep count for you.'], inspections: ['No watch on her body shows the same hour.', 'Her pulse ticks audibly.', 'She tilts her head like a second hand.'], behaviors: ['Corrects clocks by touch.', 'Says dawn is negotiable.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'botanist', tier: 'random', name: 'Leah Moss', kind: 'human', personality: 'curious, distracted', appearance: 'botanist in a moss-green coat with sample jars', backstory: 'Leah found alpine flowers blooming warm under fresh snow around a body-shaped hollow.', dialogue: ['Plants know when soil is wrong. The forest is wrong tonight.'], inspections: ['Sample jars clink in her pack.', 'Green stains mark her fingertips.', 'She names trees like old friends.'], behaviors: ['Studies bark scratches.', 'Warns when pine needles point inward.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'judge', tier: 'random', name: 'Miriam Gavel', kind: 'human', personality: 'stern, fair', appearance: 'retired judge with a black fur hat', backstory: 'Miriam sentenced a fraud years ago and heard his voice pleading outside her window after his death.', dialogue: ['Mercy without judgment is just fear wearing a nicer coat.'], inspections: ['Her cane handle is shaped like scales.', 'She has memorized everyone’s contradictions.', 'Her boots are polished beneath the snow.'], behaviors: ['Questions guests like witnesses.', 'Remembers exact testimony across nights.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'dancer', tier: 'random', name: 'Alina Step', kind: 'human', personality: 'graceful, jumpy', appearance: 'dancer with silver shoes tied around her neck', backstory: 'Alina escaped a ballroom where the music continued after the orchestra froze.', dialogue: ['My feet kept moving after I stopped wanting them to. I need a chair.'], inspections: ['Her ankles are bruised in hand shapes.', 'Silver shoes knock together softly.', 'She counts under her breath.'], behaviors: ['Hears rhythm in roof sounds.', 'Recoils from waltz-like knocking.'], stayNights: [1, 2], outcome: 'injure' },
  { id: 'butcher', tier: 'random', name: 'Karel Bone', kind: 'skinwalker', personality: 'warm, predatory', appearance: 'butcher in a red apron beneath a winter coat', backstory: 'Something copied Karel after learning that meat shops know every household by appetite.', dialogue: ['A cabin needs a stocked pantry. I can help you decide what keeps.'], inspections: ['His apron stains are too fresh.', 'A cleaver outline shows under his coat.', 'He inhales when people speak.'], behaviors: ['Comments on guests as cuts of meat.', 'Offers to sharpen kitchen knives.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'librarian', tier: 'random', name: 'Maud Page', kind: 'human', personality: 'dry, brave', appearance: 'librarian with frost-webbed spectacles', backstory: 'Maud locked the library when books began adding chapters about readers’ deaths.', dialogue: ['I have overdue books and a will to live. Both brought me here.'], inspections: ['Index cards fill her sleeves.', 'Her glasses are cracked at both lenses.', 'She smells of paper and cold ashes.'], behaviors: ['Catalogs strange events.', 'Finds matching stories in old books.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'actor', tier: 'random', name: 'Felix Mask', kind: 'skinwalker', personality: 'charming, theatrical', appearance: 'actor with stage makeup melting under snow', backstory: 'A mimic learned performance from a touring actor and never learned when to leave the stage.', dialogue: ['You want sincerity? How fortunate. I rehearsed sincerity all afternoon.'], inspections: ['Makeup covers a face that seems unfinished.', 'He bows after answering simple questions.', 'His tears run upward into his lashes.'], behaviors: ['Imitates guests for applause.', 'Repeats private lines in perfect voices.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'pilot', tier: 'random', name: 'Rhea Cloud', kind: 'human', personality: 'focused, shaken', appearance: 'bush pilot in a leather cap and cracked goggles', backstory: 'Rhea crash-landed after her compass spun toward a light under the snow.', dialogue: ['If I say I fell from the sky, will that sound more or less believable tonight?'], inspections: ['Aviation fuel clings to her coat.', 'Her goggles are starred with cracks.', 'She tracks wind direction by habit.'], behaviors: ['Predicts storm shifts.', 'Draws escape routes from above.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'fisherwife', tier: 'random', name: 'Nessa Pike', kind: 'human', personality: 'sharp, grieving', appearance: 'fisherwife in oilskin sleeves and a knitted cap', backstory: 'Nessa followed her missing wife’s lantern across the frozen reservoir.', dialogue: ['The dead do not wave with the wrong hand. I followed anyway. Love is stupid.'], inspections: ['Salt stains mark her sleeves despite mountain snow.', 'A wedding photo is sewn into her cap.', 'Her voice hardens when pitied.'], behaviors: ['Calls out false loved ones.', 'Keeps a knife under the table.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'barber', tier: 'random', name: 'Otto Shear', kind: 'skinwalker', personality: 'chatty, invasive', appearance: 'barber with a striped scarf and shining scissors', backstory: 'This visitor learned intimacy from a barber chair and asks questions too close to skin.', dialogue: ['Everyone tells a barber the truth eventually. You may start whenever.'], inspections: ['His scissors are warm and spotless.', 'Hair clippings cling to his cuffs.', 'He leans toward your throat when listening.'], behaviors: ['Offers trims during emergencies.', 'Collects fallen hair from chairs.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'geologist', tier: 'random', name: 'Dina Shale', kind: 'human', personality: 'rational, fraying', appearance: 'geologist with rock samples weighing down her pack', backstory: 'Dina found stones arranged in a circle that repeated her childhood bedroom dimensions.', dialogue: ['I believe in pressure, time, and evidence. I am revising the list.'], inspections: ['Her pack thumps with labeled stones.', 'A hand lens hangs around her neck.', 'She keeps saying impossible under her breath.'], behaviors: ['Tests ash and soil.', 'Gets angry when facts bend.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'violinist', tier: 'random', name: 'Sasha Bow', kind: 'human', personality: 'sensitive, proud', appearance: 'violinist cradling a case under her coat', backstory: 'Sasha heard her own violin answering from the forest in notes no human hand could play.', dialogue: ['I will not play tonight. Something outside already knows the song.'], inspections: ['Her violin case is warmer than her hands.', 'Rosin dust coats her collar.', 'She reacts to pitch more than words.'], behaviors: ['Identifies copied voices by rhythm.', 'Uses music to steady Tomas if present.'], stayNights: [1, 3], outcome: 'peaceful', knows: ['student'] },
  { id: 'tailor', tier: 'random', name: 'Boris Hem', kind: 'human', personality: 'vain, kind', appearance: 'tailor in a beautiful coat with mismatched buttons', backstory: 'Boris made mourning clothes for people who arrived to order them before dying.', dialogue: ['This coat was expensive and has survived worse company than yours. Please open.'], inspections: ['Each button comes from a different uniform.', 'His measuring tape is marked in red ink.', 'He judges sleeve lengths during terror.'], behaviors: ['Notices copied clothing errors.', 'Compliments anyone near tears.'], stayNights: [1, 2], outcome: 'steal' },
  { id: 'oracle', tier: 'random', name: 'Mara Ink', kind: 'skinwalker', personality: 'mystic, cruel', appearance: 'fortune teller with tattooed hands and moon earrings', backstory: 'A mimic found a fortune teller’s tent and kept only the habit of being believed.', dialogue: ['I saw you open the door. I saw you refuse. Both versions screamed.'], inspections: ['Her palm lines shift when she flexes.', 'Moon earrings show different phases.', 'She smells of candle smoke without flame.'], behaviors: ['Predicts recent events as prophecies.', 'Turns guests against their memories.'], stayNights: [1, 2], outcome: 'peaceful' },
];
