import type { GameCharacter } from './types';

export const randomCharactersC: GameCharacter[] = [
  { id: 'candlemaker', tier: 'random', name: 'Pavel Wax', kind: 'human', personality: 'humble, frightened', appearance: 'candlemaker with wax-sealed gloves', backstory: 'Pavel’s candles began burning blue whenever someone lied near them.', dialogue: ['I can give you light that tattles, if it survives my pocket.'], inspections: ['Wax seals every glove seam.', 'Blue candle stubs fill a tin.', 'His sleeves smell of lavender and smoke.'], behaviors: ['Tests stories with candle flame.', 'Panics when flames bend toward guests.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'climber', tier: 'random', name: 'Jo Ridge', kind: 'human', personality: 'bold, shaken', appearance: 'mountain climber with a torn rope over one shoulder', backstory: 'Jo cut a rope after the person below started climbing without hands.', dialogue: ['I made one terrible choice already tonight. I would like this one to be better.'], inspections: ['Her rope end is cleanly cut.', 'Ice crystals pack her eyelashes.', 'Her knuckles are split from gripping stone.'], behaviors: ['Checks ceiling beams for anchor points.', 'Distrusts visitors with clean hands.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'clown', tier: 'random', name: 'Pip Cinder', kind: 'skinwalker', personality: 'playful, rancid', appearance: 'circus clown with soot-blackened ruffles', backstory: 'A thing crawled from a burned fairground trailer wearing laughter like a mask.', dialogue: ['Bad weather for comedy. Excellent weather for doors.'], inspections: ['Paint cracks around a too-wide mouth.', 'Tiny bells on his cuffs make no sound.', 'Soot falls from dry sleeves.'], behaviors: ['Laughs when no one moves.', 'Gives guests nicknames they hate.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'archivist', tier: 'random', name: 'Selene Quarto', kind: 'human', personality: 'scholarly, intense', appearance: 'archivist with a leather document tube', backstory: 'Selene found town records edited overnight to include citizens who never existed.', dialogue: ['History has started revising itself. I object professionally.'], inspections: ['Her document tube is locked twice.', 'Ink stains form dates on her fingers.', 'She speaks like footnotes are chasing her.'], behaviors: ['Cross-checks names with records.', 'Recognizes fake family histories.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'firefighter', tier: 'random', name: 'Anton Hale', kind: 'human', personality: 'steady, haunted', appearance: 'firefighter with smoke-stained turnout pants', backstory: 'Anton searched a burned lodge and found wet footprints circling the ashes.', dialogue: ['Smoke I understand. Snow that smells like smoke, I do not.'], inspections: ['His coat is scorched at one sleeve.', 'A rescue whistle hangs at his chest.', 'His hands shake only after danger passes.'], behaviors: ['Checks chimney drafts.', 'Takes charge when guests panic.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'magician', tier: 'random', name: 'Victor Vanish', kind: 'skinwalker', personality: 'slick, needling', appearance: 'magician in a purple scarf and cracked top hat', backstory: 'This mimic learned misdirection from posters left inside a collapsed theater.', dialogue: ['A locked door is just a trick waiting for applause. Shall we?'], inspections: ['Cards spill from his sleeves without falling.', 'His hat is full of packed snow.', 'He smiles whenever you look away.'], behaviors: ['Makes small objects disappear.', 'Calls survival a performance.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'dentist', tier: 'random', name: 'Helena Root', kind: 'human', personality: 'calm, unsettling', appearance: 'dentist with a white case and red scarf', backstory: 'Helena identified a monster when it copied a patient but forgot three fillings.', dialogue: ['Teeth are honest. If anyone smiles too long, send them to me.'], inspections: ['Her case rattles with metal tools.', 'Her scarf is tied like a surgical mask.', 'She notices your molars when you speak.'], behaviors: ['Checks bites in food.', 'Warns Silas if present about dental proof.'], stayNights: [1, 2], outcome: 'peaceful', knows: ['undertaker'] },
  { id: 'carpenter', tier: 'random', name: 'Milo Beam', kind: 'human', personality: 'helpful, wary', appearance: 'carpenter with nail pouches over a parka', backstory: 'Milo built barricades in town until one knocked back from the wrong side.', dialogue: ['Your frame is good. Your threshold is nervous. I can work with one of those.'], inspections: ['Nails line his pockets by size.', 'His hammer handle is cracked.', 'He judges the door with professional pity.'], behaviors: ['Reinforces the living room door.', 'Hears weak boards before they groan.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'newscaster', tier: 'random', name: 'Lana Bright', kind: 'human', personality: 'polished, terrified', appearance: 'newscaster in a red coat with mascara tracks', backstory: 'Lana broadcast evacuation orders until a second Lana began speaking between sentences.', dialogue: ['This is Lana Bright reporting that I am absolutely not fine.'], inspections: ['Her microphone is dead but gripped tightly.', 'Mascara freezes on her cheeks.', 'She narrates when afraid.'], behaviors: ['Reports room events under her breath.', 'Spots repeated phrases in visitors.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'perfumer', tier: 'random', name: 'Odette Bloom', kind: 'skinwalker', personality: 'luxurious, predatory', appearance: 'perfumer in a cream coat smelling of roses', backstory: 'A mimic learned people can be tracked by grief, sweat, and perfume.', dialogue: ['Fear has notes. Yours begins sharp, then turns sweet.'], inspections: ['Rose scent cuts through the smoke.', 'Her gloves are stained with amber oil.', 'She names emotions by smell.'], behaviors: ['Sniffs guests as they pass.', 'Claims mimics smell empty.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'watchman', tier: 'random', name: 'Uri Night', kind: 'human', personality: 'paranoid, loyal', appearance: 'night watchman with a dented thermos', backstory: 'Uri guarded the ski lift and saw chairs rising uphill with people sitting backward.', dialogue: ['I am good at staying awake. Tonight that feels like a marketable skill.'], inspections: ['His thermos is full of bitter coffee.', 'Binocular marks ring his eyes.', 'Keys jangle at every breath.'], behaviors: ['Takes late watches.', 'Wakes everyone when shadows change.'], stayNights: [1, 3], outcome: 'peaceful' },
  { id: 'grocer', tier: 'random', name: 'Iman Crate', kind: 'human', personality: 'generous, fretful', appearance: 'grocer with twine-wrapped boxes strapped to her sled', backstory: 'Iman’s store shelves restocked themselves with labels written in missing people’s handwriting.', dialogue: ['I have tins, matches, and a bad feeling about the pears.'], inspections: ['Twine burns mark her wrists.', 'Her inventory list includes crossed-out names.', 'She smells of oranges and damp cardboard.'], behaviors: ['Shares supplies if trusted.', 'Counts cans after every guest arrives.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'gravekeeper', tier: 'random', name: 'Edwin Moss', kind: 'human', personality: 'morbid, gentle', appearance: 'gravekeeper with a shovel and knitted earflaps', backstory: 'Edwin found fresh graves opened from below with the snow placed neatly back on top.', dialogue: ['I am not afraid of graves. I am afraid of empty ones.'], inspections: ['Frozen dirt cakes his boots.', 'His shovel blade is polished bright.', 'He smells of cedar chips.'], behaviors: ['Notices cemetery dirt on visitors.', 'Speaks softly to the frightened.'], stayNights: [1, 3], outcome: 'peaceful', knows: ['undertaker'] },
  { id: 'puppeteer', tier: 'random', name: 'Nico String', kind: 'skinwalker', personality: 'soft, manipulative', appearance: 'puppeteer with wooden dolls tied to his pack', backstory: 'Something copied Nico after learning how easy bodies look when moved from above.', dialogue: ['People are gentler when they remember they are held by something.'], inspections: ['Doll strings knot around his wrists.', 'One puppet has your coat color.', 'His elbows bend slightly late.'], behaviors: ['Makes puppets repeat arguments.', 'Claims guests are being guided.'], stayNights: [1, 2], outcome: 'peaceful' },
  { id: 'chemist', tier: 'random', name: 'Dr. Alma Vial', kind: 'human', personality: 'brilliant, impatient', appearance: 'chemist with fogged goggles and a metal sample case', backstory: 'Alma tested melted snow and found traces of blood from people still alive.', dialogue: ['I have proof the storm is biologically rude. Let me in and I will explain poorly.'], inspections: ['Glass vials clink in foam slots.', 'Her goggles are fogged from panic.', 'Chemical stains dot her gloves.'], behaviors: ['Tests snow samples.', 'Insults impossible phenomena until less scared.'], stayNights: [1, 3], outcome: 'peaceful' },
];
