import type { GameCharacter } from './types';

export const rareCharacters: GameCharacter[] = [
  { id: 'mirror-child', tier: 'rare', name: 'The Mirror Child', kind: 'skinwalker', personality: 'quiet, imitative', appearance: 'small child in pajamas reflecting firelight from both eyes', backstory: 'It appears only after enough people sleep inside, as if copied from the room’s idea of safety.', dialogue: ['I woke up in your mirror. Can I sleep where the glass cannot see me?'], inspections: ['Its feet are dry and bare.', 'Its eyes reflect rooms behind you.', 'It repeats the last kind word spoken here.'], behaviors: ['Copies the safest guest’s voice.', 'Appears when the cabin feels crowded.'], stayNights: [1, 1], rareCondition: 'afterMimicInside' },
  { id: 'white-stag-man', tier: 'rare', name: 'Elias Antler', kind: 'skinwalker', personality: 'ancient, courteous', appearance: 'tall man with antler shadows moving behind his hood', backstory: 'Old hunters mention Elias as the shape that asks permission because permission tastes better.', dialogue: ['You have kept a warm house in a hungry place. That is almost rude.'], inspections: ['Antler shadows move without antlers.', 'Snow melts before touching his coat.', 'His voice makes the floorboards bow.'], behaviors: ['Speaks to Caleb like an old rival.', 'Leaves hoof marks after using human feet.'], stayNights: [1, 1], knows: ['hunter'], rareCondition: 'late' },
  { id: 'lost-astronaut', tier: 'rare', name: 'Mira Cosmon', kind: 'human', personality: 'dazed, poetic', appearance: 'woman in an obsolete pressure suit under a parka', backstory: 'Mira claims she fell through a white sky above a country that no longer exists.', dialogue: ['Your mountain is not the strangest place I have been, but it is trying very hard.'], inspections: ['Her helmet visor is cracked from inside.', 'A mission patch shows no known flag.', 'Her breath smells faintly of ozone.'], behaviors: ['Recognizes stars hidden by clouds.', 'Calls the storm an atmosphere with intentions.'], stayNights: [1, 2], outcome: 'peaceful', rareCondition: 'storm' },
  { id: 'hollow-saint', tier: 'rare', name: 'Saint Orra', kind: 'skinwalker', personality: 'serene, merciless', appearance: 'saintly figure wrapped in gold-threaded funeral cloth', backstory: 'A chapel mural peeled from the wall one winter and began asking for shelter.', dialogue: ['Open, and be rewarded with certainty. Refuse, and keep your little doubt.'], inspections: ['Gold thread pulses like veins.', 'No snow rests on the funeral cloth.', 'Its smile is painted more than made.'], behaviors: ['Turns prayers into threats.', 'Makes Father Emil doubt his memory.'], stayNights: [1, 1], knows: ['priest'], rareCondition: 'manyRefusals' },
  { id: 'radio-host', tier: 'rare', name: 'Marina Static', kind: 'human', personality: 'fast-talking, brittle', appearance: 'radio host with headphones around her neck', backstory: 'Marina broadcast from a station that vanished from its hill, leaving only her signal.', dialogue: ['Caller, you are live on the worst night of my career. Please say yes.'], inspections: ['Static crackles from dead headphones.', 'Her throat is raw from talking.', 'Station call letters are scratched off her badge.'], behaviors: ['Narrates danger through radio habits.', 'Hears June’s broken radio answer.'], stayNights: [1, 2], outcome: 'peaceful', knows: ['ranger'], rareCondition: 'late' },
  { id: 'snow-queen', tier: 'rare', name: 'Queen Under Ice', kind: 'skinwalker', personality: 'regal, starving', appearance: 'woman in a crown of frozen twigs and veil of frost', backstory: 'No one agrees whether she is a person, a title, or the storm practicing royalty.', dialogue: ['Little hearthkeeper, your guests have made my forest untidy.'], inspections: ['Her crown grows through her hair.', 'Frost patterns follow her gaze.', 'She treats the threshold like a court line.'], behaviors: ['Commands mimics without naming them.', 'Makes brave guests kneel without knowing why.'], stayNights: [1, 1], rareCondition: 'late' },
  { id: 'debt-collector', tier: 'rare', name: 'Mr. Cleft', kind: 'skinwalker', personality: 'legalistic, patient', appearance: 'thin man in a black suit with snow in every pocket', backstory: 'Mr. Cleft visits when supplies run low and offers bargains whose costs arrive later.', dialogue: ['I understand scarcity. I specialize in fair trades and unfair necessities.'], inspections: ['Contracts are stitched into his lining.', 'His smile divides slightly at the center.', 'He knows exactly how many supplies remain.'], behaviors: ['Offers food for names.', 'Calls every kindness a debt.'], stayNights: [1, 1], rareCondition: 'lowSupplies' },
  { id: 'returning-dead', tier: 'rare', name: 'Alina Grey', kind: 'skinwalker', personality: 'tender, wrong', appearance: 'dead woman wearing a guest’s remembered coat', backstory: 'This visitor can resemble someone the player refused, using guilt as a lantern.', dialogue: ['You closed the door so carefully. I appreciated the manners.'], inspections: ['Her coat changes when you blink.', 'Her voice carries snow-packed silence.', 'She remembers choices, not life.'], behaviors: ['Quotes previous refusals.', 'Makes human guests accuse you.'], stayNights: [1, 1], rareCondition: 'manyRefusals' },
  { id: 'black-dog', tier: 'rare', name: 'The Black Dog', kind: 'human', personality: 'wordless, loyal', appearance: 'large black dog with ice in its fur and human sadness in its eyes', backstory: 'The dog follows doomed travelers and sometimes reaches shelter before the truth does.', dialogue: ['The dog presses its head to the door and whines like a warning.'], inspections: ['Its paws are cut from walking on ice.', 'A broken collar reads HOME.', 'It growls at empty corners.'], behaviors: ['Warns about mimics inside.', 'Sleeps against the coldest wall.'], stayNights: [1, 2], outcome: 'peaceful', rareCondition: 'storm' },
  { id: 'author', tier: 'rare', name: 'The Author', kind: 'skinwalker', personality: 'intimate, smug', appearance: 'faceless writer with a notebook bound in gray cloth', backstory: 'A thing that may have written the cabin’s nightmares sometimes asks to revise them in person.', dialogue: ['I know how this night ends. I came to see whether you improvise.'], inspections: ['Its notebook contains your latest choice.', 'Where its face should be, snow falls inward.', 'Ink drips upward from the pen.'], behaviors: ['Changes dialogue by finishing sentences.', 'References endings the player has not seen.'], stayNights: [1, 1], rareCondition: 'late' },
];
